name: ChunkClaimer
main: com.github.CubieX.ChunkClaimer.ChunkClaimer
author: CubieX
depend: [WorldEdit, WorldGuard]
softdepend: [PermissionsEx, zPermissions, bPermissions, PermissionsBukkit]
version: 0.0.1
description: Chunk claiming system designed for usage in the freebuild by normal members

commands:
    cclaimer:
      description: Using ChunkFinder
      aliases: chunk
      usage: /cclaimer version | reload | help

permissions:
    chunkclaimer.buy:
        description: Grants ability to buy a chunk and gaining its ownership
        default: op
    chunkclaimer.sell:
        description: Grants ability to sell a chunk and transfer ownership
        default: op
    chunkclaimer.addfriend:
        description: Grants ability to add a friend to an owned chunk
        default: op
    chunkclaimer.removefriend:
        description: Grants ability to remove a friend from an owned chunk
        default: op
    chunkclaimer.override:
        description: Grants ability to build on a chunk not owned
        default: op
    chunkclaimer.admin:
        description: Allows total control over the plugin
        default: op