name: ChunkClaimer
main: com.github.CubieX.ChunkClaimer.ChunkClaimer
author: CubieX
depend: [WorldEdit, WorldGuard]
softdepend: [PermissionsEx, zPermissions, bPermissions, PermissionsBukkit, Vault, iConomy]
version: 0.4.0
description: Chunk claiming system designed for usage in the freebuild by normal members

commands:
    cclaimer:
      description: Using ChunkClaimer
      aliases: chunk
      usage: /cclaimer kaufen | verkaufen [preis] | addfriend <spieler> | removefriend <spieler> | liste [seite]| version | reload | help

permissions:
    chunkclaimer.buy:
        description: Grants ability to buy a chunk and gaining its ownership
        default: op
    chunkclaimer.sell:
        description: Grants ability to sell a chunk and transfer ownership
        default: op
    chunkclaimer.manage:
        description: Grants ability to add and remove friends for any CC region
        default: op
        children:
          chunkclaimer.buy: true
          chunkclaimer.sell: true         
    chunkclaimer.admin:
        description: Allows total control over the plugin
        default: op
        children:
          chunkclaimer.manage: true